import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowDownToLine, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Database, ExternalLink, FlaskConical, LayoutGrid, List, LoaderCircle, Plus, RefreshCw, Settings2, ShieldCheck, SlidersHorizontal, X } from 'lucide-react'
import type { Bet, Board, Evaluation, Market, Mode, Pick, Quote, Row, Settings } from './types'
import './style.css'

const money = (v:number|string|null|undefined) => v == null ? '—' : Number(v).toLocaleString('en-US',{style:'currency',currency:'USD'})
const pct = (v:number|null|undefined, signed=false) => v == null ? '—' : `${signed && v>0?'+':''}${v.toFixed(2)}%`
const price = (d:number|null|undefined) => d ? (d>=2?`+${Math.round((d-1)*100)}`:`${Math.round(-100/(d-1))}`) : '—'
const lineText = (p:Pick,g:Row['game']) => p.market==='total'?`${p.side==='over'?'Over':'Under'} ${p.line}`:`${g[p.side as 'home'|'away']}${p.market==='spread'?` ${p.line!>0?'+':''}${p.line}`:''}`
const marketName = (m:Market) => ({moneyline:'Moneyline',spread:'Spread',total:'Total'}[m])
const keyOf = (p:Pick) => `${p.game_id}-${p.market}-${p.side}-${p.line}`
const shortTime = (s:string) => new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})
const ageText = (s:string|null|undefined,now:number) => {if(!s)return 'Not collected';const sec=Math.max(0,Math.floor((now-new Date(s).getTime())/1000));return sec<60?`${sec}s ago`:sec<3600?`${Math.floor(sec/60)}m ago`:`${Math.floor(sec/3600)}h ago`}
async function api<T>(path:string,method='GET',body?:unknown):Promise<T> {
  const res = await fetch(`/api/${path}`,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined})
  if(!res.ok) { const e=await res.json().catch(()=>({detail:`Request failed (${res.status})`})); throw new Error(typeof e.detail==='string'?e.detail:e.detail?.map((d:{msg:string})=>d.msg).join('; ') || 'Request failed') }
  return res.json()
}
function App(){
  const [board,setBoard]=useState<Board|null>(null),[view,setView]=useState('board'),[market,setMarket]=useState<Market>('moneyline')
  const [selected,setSelected]=useState<Row|null>(null),[bets,setBets]=useState<Bet[]>([]),[mode,setMode]=useState<Mode>('paper')
  const [now,setNow]=useState(Date.now()),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('')
  const pending=useRef(false)
  const load=async()=>{if(pending.current)return;pending.current=true;try{const [b,j]=await Promise.all([api<Board>('board'),api<Bet[]>('bets')]);setBoard(b);setBets(j);setError('')}catch(e){setError((e as Error).message)}finally{pending.current=false}}
  useEffect(()=>{void load();const t=setInterval(()=>void load(),30000);const clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(t);clearInterval(clock)}},[])
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(t)},[notice])
  const refresh=async()=>{setBusy(true);try{const r=await api<{status:string;retry_seconds?:number}>('refresh','POST');setNotice(r.status==='cooldown'?`Refresh available in ${r.retry_seconds}s.`:r.status==='running'?'Collection is already running.':'Reference prices refreshed.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const stage=(r:Row)=>{setView('board');setMarket(r.market);setSelected(r)}
  // Optional browser-local tools stage UI state; they never submit a wager or save an actual entry.
  useEffect(()=>{
    const mc=(document as unknown as {modelContext?:{registerTool:(t:unknown)=>void;unregisterTool?:(name:string)=>void}}).modelContext
    if(!mc)return
    const tools=[{name:'read_nfl_board',description:'Read the local NFL reference board and source limitations.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify(await api<Board>('board'))}]})},
      {name:'stage_nfl_quote',description:'Open the quote checker for a visible selection. Does not place or log a bet.',inputSchema:{type:'object',properties:{selectionKey:{type:'string'}},required:['selectionKey']},execute:async({selectionKey}:{selectionKey:string})=>{const row=board?.rows.find(r=>keyOf(r)===selectionKey);if(!row)throw new Error('Selection not found');stage(row);return {content:[{type:'text',text:'Quote checker opened; enter the actual Underdog slip values.'}]}}}]
    try{tools.forEach(t=>mc.registerTool(t))}catch{ /* Browser support varies; the ordinary interface remains complete. */ }
    return()=>tools.forEach(t=>mc.unregisterTool?.(t.name))
  },[board])
  const rows=board?.rows.filter(r=>r.market===market && `${r.game.home_name} ${r.game.away_name}`.toLowerCase().includes(search.toLowerCase()))||[]
  const current=bets.filter(b=>b.quote.mode===mode),settled=current.filter(b=>b.settlement)
  const pnl=settled.reduce((sum,b)=>sum+b.settlement!.pnl,0),staked=settled.reduce((sum,b)=>sum+Number(b.quote.total_cost),0)
  const eligibleGames=new Set(board?.rows.filter(r=>r.eligible_count>=board.settings.min_books).map(r=>r.game_id)).size
  return <div className="shell">
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e=>{e.preventDefault();setView('board')}} aria-label="NFL Edge home"><span className="brandmark">↗</span><span>NFL<span className="brand-light">Edge</span><small>PRICE RESEARCH</small></span></a>
      <div className="workspace-label">YOUR WORKSPACE</div>
      <nav aria-label="Main navigation">{[{id:'board',name:'Odds board',icon:LayoutGrid},{id:'journal',name:'Bet journal',icon:BookOpen},{id:'sources',name:'Data & method',icon:Database},{id:'settings',name:'Settings',icon:SlidersHorizontal}].map(n=><button key={n.id} className={view===n.id?'nav-item active':'nav-item'} onClick={()=>setView(n.id)}><n.icon size={18}/><span>{n.name}</span>{n.id==='journal'&&<span className="nav-count">{bets.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><span className="local-dot"/> Running locally<small>Private database · Free sources</small><div className="scope">NFL · Pregame · Full game<br/>Manual placement on Underdog</div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/> <strong>{{board:'Odds board',journal:'Bet journal',sources:'Data & method',settings:'Settings'}[view]}</strong></div><span className="chip neutral"><FlaskConical size={13}/> Research workspace</span></header>
      <div className="content">
        {error&&<div className="message error" role="alert">{error}<button onClick={()=>void load()}>Retry</button></div>}
        {notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
        <div className="page-heading"><div><div className="eyebrow">{view==='board'?'THE PRICE IS THE STARTING POINT':'YOUR LOCAL WORKSPACE'}</div><h1>{{board:'Find the price advantage.',journal:'Every entry. Every outcome.',sources:'Know what is behind the number.',settings:'Set your research rules.'}[view]}</h1><p>{{board:'Compare NFL prices, check an Underdog quote, and keep the evidence.',journal:'Entry estimates stay fixed. Results and closing comparisons tell the next part.',sources:'Coverage, freshness, and assumptions are visible at every step.',settings:'These settings control estimates and exposure across your local workspace.'}[view]}</p></div>{view==='board'&&<button className="button primary" onClick={()=>void refresh()} disabled={busy||board?.refreshing}><RefreshCw size={16} className={busy||board?.refreshing?'spin':''}/>{busy||board?.refreshing?'Collecting…':'Refresh prices'}</button>}</div>
        {!board?<div className="loading"><LoaderCircle className="spin"/>Loading your local workspace…</div>:<>
          {view==='board'&&<>
            <section className="summary-grid" aria-label="Workspace summary">
              <div><span>Upcoming games</span><strong>{new Set(board.rows.map(r=>r.game_id)).size}<small>NFL · next 14 days</small></strong></div>
              <div><span>Automated book references</span><strong>2<small>+ Kalshi comparison</small></strong></div>
              <div><span>Games with sufficient fresh evidence</span><strong>{eligibleGames}<small>{board.settings.min_books} books required per selection</small></strong></div>
              <div><span>Configured bankroll</span><strong>{Number(board.settings.bankroll)?money(board.settings.bankroll):'Not set'}<button className="text-button" onClick={()=>setView('settings')}>{Number(board.settings.bankroll)?'Edit settings':'Set bankroll'} <ArrowRight size={12}/></button></strong></div>
            </section>
            <div className="board-layout">
              <section className="panel board-panel">
                <div className="panel-heading"><div><h2>Market board</h2><span className="subtle">Reference prices · all times local</span></div><span className="chip neutral">Pregame</span></div>
                <div className="board-controls"><div className="segmented" aria-label="Market type">{(['moneyline','spread','total'] as Market[]).map(m=><button key={m} className={m===market?'selected':''} onClick={()=>setMarket(m)}>{marketName(m)}</button>)}</div><input className="search" aria-label="Filter teams" placeholder="Filter teams…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
                <div className="table-scroll"><table className="odds-table"><thead><tr><th>GAME / SELECTION</th><th>DRAFTKINGS <small>via ESPN</small></th><th>BOVADA <small>direct board</small></th><th>FAIR EST.<small>margin removed</small></th><th>EVIDENCE<small>fresh books</small></th><th><span className="sr-only">Check quote</span></th></tr></thead><tbody>
                  {rows.map((r,i)=>{const prev=rows[i-1],newGame=prev?.game_id!==r.game_id;return <React.Fragment key={keyOf(r)}>{newGame&&<tr className="game-divider"><td colSpan={6}><span>{r.game.away} <span className="versus">at</span> {r.game.home}</span><time>{shortTime(r.game.start_time)}</time></td></tr>}<tr className={selected&&keyOf(selected)===keyOf(r)?'picked-row':''}><td><button className="selection-button" onClick={()=>stage(r)}><span className={`team-token ${r.side==='home'||r.side==='under'?'home-token':''}`}>{r.market==='total'?(r.side==='over'?'O':'U'):r.game[r.side as 'home'|'away']}</span><span><strong>{lineText(r,r.game)}</strong><small>{r.market==='total'?'Combined points':r.game[`${r.side}_name` as 'home_name'|'away_name']}</small></span></button></td>{['DraftKings','Bovada'].map(b=>{const ref=r.references.find(q=>q.book===b);return <td key={b} className="number" title={ref?`${ageText(ref.observed_at,now)} · ${ref.reason||'Current observation'}`:'No matching pair'}>{price(ref?.decimal_price)}{ref&&<small>{ageText(ref.observed_at,now)}</small>}</td>})}<td className="number">{r.probability==null?'—':pct(r.probability*100)}<small>{r.probability==null?'Push data needed':'Market estimate'}</small></td><td><span className={`evidence-count ${r.eligible_count>=board.settings.min_books?'enough':''}`}>{r.eligible_count}/{board.settings.min_books}</span><small className="subtle">{r.eligible_count>=board.settings.min_books?'Check quote':'Research only'}</small></td><td><button className="row-action" aria-label={`Check ${lineText(r,r.game)} ${marketName(r.market)} quote`} onClick={()=>stage(r)}><ArrowRight size={17}/></button></td></tr></React.Fragment>})}
                </tbody></table>{!rows.length&&<div className="empty"><LayoutGrid size={26}/><h3>{search?'No matching teams':'No upcoming prices available'}</h3><p>{search?'Try another team name.':'Refresh prices or check Data & method for source status.'}</p></div>}</div>
                <footer className="board-footer"><span><CircleHelp size={14}/> Best displayed payout alone does not establish +EV.</span><button className="text-button" onClick={()=>setView('sources')}>How estimates work <ArrowRight size={13}/></button></footer>
              </section>
              <aside className="context-rail"><div className="rail-card"><span className="eyebrow">YOUR WORKFLOW</span><h2>From price to evidence.</h2>{[['01','Choose a selection','Compare the exact team and point line.'],['02','Enter the Underdog quote','Use total cost with fees and total winning return.'],['03','Check, then record','Review the estimate and save a paper or accepted entry.']].map(([n,h,p])=><div className="step" key={n}><span>{n}</span><div><strong>{h}</strong><p>{p}</p></div></div>)}</div><div className="rail-card tint"><Database size={21}/><h3>Coverage is still developing.</h3><p>ESPN carries DraftKings. Bovada adds one book. Kalshi is an exchange comparison.</p><p>The screen needs {board.settings.min_books} distinct, fresh sportsbook pairs. Add current reference pairs in the quote checker.</p><button className="text-button" onClick={()=>setView('sources')}>Inspect sources <ArrowRight size={13}/></button></div><div className="source-mini">{board.sources.map(s=><div key={s.id}><span className={`status-dot ${s.status}`}/><span>{s.name}</span><small>{ageText(s.last_success,now)}</small></div>)}</div></aside>
            </div>
          </>}
          {view==='journal'&&<>
            <div className="section-toolbar"><div className="segmented">{(['paper','actual'] as Mode[]).map(m=><button key={m} className={m===mode?'selected':''} onClick={()=>setMode(m)}>{m==='paper'?'Paper entries':'Actual entries'}</button>)}</div><a className="button secondary" href="/api/export.csv"><ArrowDownToLine size={16}/>Export CSV</a></div>
            <div className="summary-grid"><div><span>Entries</span><strong>{current.length}<small>{settled.length} settled</small></strong></div><div><span>Realized {mode==='paper'?'paper ':''}P&L</span><strong className={pnl>0?'positive':''}>{settled.length?money(pnl):'—'}<small>From recorded returns</small></strong></div><div><span>Realized ROI</span><strong>{staked?pct(pnl/staked*100,true):'—'}<small>Settled entry cost only</small></strong></div><div><span>Open exposure</span><strong>{money(board.exposure[mode].total_open)}<small>{mode==='paper'?'Paper':'Actual'} entries</small></strong></div></div>
            <Journal bets={current} onChange={()=>void load()} onNotice={setNotice}/>
          </>}
          {view==='sources'&&<><div className="source-grid">{board.sources.map(s=><section className="panel source-card" key={s.id}><div className="source-title"><Database size={20}/><span className={`chip ${s.status==='ok'?'good':'neutral'}`}>{s.status==='ok'?'Connected':s.status}</span></div><h2>{s.name}</h2><p className="subtle">{s.kind}</p><div className="source-stats"><strong>{s.game_count}<small>games</small></strong><strong>{s.quote_count}<small>selections</small></strong></div><dl><div><dt>Last successful observation</dt><dd>{ageText(s.last_success,now)}</dd></div><div><dt>Markets</dt><dd>{s.markets.map(m=>marketName(m as Market)).join(', ')||'Awaiting data'}</dd></div></dl><p>{s.note}</p>{s.error&&<p className="error-copy">{s.error}</p>}{s.skipped>0&&<p className="subtle">{s.skipped} unsupported or malformed events skipped.</p>}<a href={s.url} target="_blank" rel="noreferrer" className="text-button">Source details <ExternalLink size={13}/></a></section>)}</div><section className="panel method"><div><span className="eyebrow">THE METHOD</span><h2>A price estimate with visible assumptions.</h2><p>For each sportsbook, we convert both sides to implied probabilities and remove its margin proportionally. We take the median across distinct books at the exact same line. This is an estimate of fair probability.</p><div className="formula">Estimated EV = expected total return − all-in cost</div><p>A fair 50/50 bet at −115 has an expected ROI of <strong>−6.52%</strong>. A larger payout can still be a losing price if its probability is low enough.</p></div><div><h3>What earns a screen pass?</h3><ul><li>At least {board.settings.min_books} distinct eligible sportsbook pairs, observed within {board.settings.max_age_seconds} seconds.</li><li>Conservative estimated ROI ≥ {board.settings.min_roi_pct}%, and positive after a {board.settings.stress_pp} percentage-point probability reduction.</li><li>Confirmed fees and full-game rules, exact lines, and a fresh Underdog quote.</li></ul><p>Moneyline ties use a configurable 0–{board.settings.tie_max_pct}% sensitivity range. Integer spreads and totals require adjacent half-point pairs and a confirmed push return.</p><p>CLV compares the accepted entry with a benchmark captured within five minutes before kickoff. It supports evaluation of your process; it does not prove a profitable edge.</p><a className="text-button" href="https://help.underdogsports.com/en/articles/16075547-prediction-picks-football" target="_blank" rel="noreferrer">Underdog football settlement rules <ExternalLink size={13}/></a></div></section></>}
          {view==='settings'&&<SettingsForm settings={board.settings} onSave={async s=>{await api('settings','PUT',s);await load();setNotice('Settings saved. New evaluations use these rules.')}}/>}
        </>}
        <footer className="page-footer"><span>NFL Edge <span>v0.1</span></span><span>Market estimates · Local records · Manual execution</span></footer>
      </div>
    </main>
    {selected&&board&&<QuotePanel key={keyOf(selected)} row={selected} settings={board.settings} now={now} onClose={()=>setSelected(null)} onChange={async()=>{await load()}} onNotice={setNotice}/>}
  </div>
}

function QuotePanel({row,settings,now,onClose,onChange,onNotice}:{row:Row;settings:Settings;now:number;onClose:()=>void;onChange:()=>Promise<void>;onNotice:(s:string)=>void}){
  const [form,setForm]=useState<Quote>({game_id:row.game_id,market:row.market,side:row.side,line:row.line,total_cost:'',winning_payout:'',observed_at:new Date().toISOString(),exchange:'Unknown',fees_confirmed:false,rules_confirmed:false,push_return:null,mode:'paper'})
  const [result,setResult]=useState<Evaluation|null>(null),[tab,setTab]=useState('quote'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[placed,setPlaced]=useState(false),[notes,setNotes]=useState('')
  const panel=useRef<HTMLDivElement>(null)
  useEffect(()=>{const prior=document.activeElement as HTMLElement|null;panel.current?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select, textarea, a[href]')||[]);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handle);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=old;prior?.focus()}},[])
  const change=(update:Partial<Quote>)=>{setForm(f=>({...f,...update}));setResult(null);setError('');setPlaced(false)}
  const integer=form.market!=='moneyline'&&form.line!=null&&Number.isInteger(form.line)
  const fresh=now-new Date(form.observed_at).getTime()<=settings.max_age_seconds*1000
  const check=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{setResult(await api<Evaluation>('evaluate','POST',form))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const save=async()=>{setBusy(true);setError('');try{await api('bets','POST',{...form,placed_confirmed:placed,notes});await onChange();onNotice(`${form.mode==='paper'?'Paper':'Accepted'} entry saved to the journal.`);onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="quote-panel" role="dialog" aria-modal="true" aria-labelledby="quote-title" tabIndex={-1} ref={panel}>
    <header className="drawer-header"><div><span className="eyebrow">UNDERDOG QUOTE CHECKER</span><h2 id="quote-title">{lineText(form,row.game)} <span>{marketName(form.market)}</span></h2><p>{row.game.away} at {row.game.home} · {shortTime(row.game.start_time)}</p></div><button className="icon-button" onClick={onClose} aria-label="Close quote checker"><X size={21}/></button></header>
    <div className="drawer-tabs"><button className={tab==='quote'?'active':''} onClick={()=>setTab('quote')}>Check a quote</button><button className={tab==='refs'?'active':''} onClick={()=>setTab('refs')}>Add reference pairs</button></div>
    <div className="drawer-body">{tab==='refs'?<ReferenceForm row={{...row,...form}} onSave={async()=>{await onChange();setResult(null);onNotice('Reference pair added. Recheck the quote to use the new evidence.')}}/>:<>
      <form onSubmit={e=>void check(e)}>
        <div className="segmented mode-switch">{(['paper','actual'] as Mode[]).map(m=><button type="button" key={m} className={form.mode===m?'selected':''} onClick={()=>change({mode:m})}>{m==='paper'?'Paper evaluation':'Accepted bet record'}</button>)}</div>
        <p className="form-intro">{form.mode==='paper'?'Read the current Underdog entry slip and enter its total values.':'Use the cost and payout actually accepted for your manually placed bet.'}</p>
        <div className="form-grid">{form.market!=='moneyline'&&<label>Exact {form.market==='spread'?'selection spread':'point total'}<input type="number" step="0.5" min={form.market==='total'?'0.5':'-150'} max="150" required value={form.line??''} onChange={e=>change({line:e.target.value===''?null:Number(e.target.value)})}/><small>Match this exact line in Underdog.</small></label>}<label>Exchange on the slip<select value={form.exchange} onChange={e=>change({exchange:e.target.value})}><option>Unknown</option><option>UDX</option><option>Kalshi</option><option>Nadex</option></select><small>Shown in market or entry details.</small></label><label>Total cost, including fees ($)<input autoComplete="off" type="number" step="0.01" min="0.01" required placeholder="e.g. 10.00" value={form.total_cost} onChange={e=>change({total_cost:e.target.value})}/></label><label>Total winning return ($)<input autoComplete="off" type="number" step="0.01" min="0.01" required placeholder="e.g. 21.00" value={form.winning_payout} onChange={e=>change({winning_payout:e.target.value})}/><small>Includes any returned stake; not profit alone.</small></label>{integer&&<label>Total returned on a push ($)<input type="number" step="0.01" min="0" required value={form.push_return??''} onChange={e=>change({push_return:e.target.value||null})}/><small>Read the applicable settlement rule.</small></label>}</div>
        <div className="observation"><div><span className={`status-dot ${fresh?'ok':'partial'}`}/><span>Quote observed {ageText(form.observed_at,now)}</span></div><button type="button" className="text-button" onClick={()=>change({observed_at:new Date().toISOString()})}>I rechecked it now</button></div>
        <label className="checkbox"><input type="checkbox" checked={form.fees_confirmed} onChange={e=>change({fees_confirmed:e.target.checked})}/><span>Total cost includes all entry fees.</span></label>
        <label className="checkbox"><input type="checkbox" checked={form.rules_confirmed} onChange={e=>change({rules_confirmed:e.target.checked})}/><span>I confirmed full-game, overtime-inclusive rules and a $0 losing return.{form.market==='moneyline'&&' A tied game returns half the winning payout.'}{integer&&' The push return above matches this market.'}</span></label>
        <button className="button primary full" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={17}/>:<ShieldCheck size={17}/>}Evaluate this quote</button>
      </form>
      {error&&<div className="message error" role="alert">{error}</div>}
      {result&&<section className={`evaluation ${result.qualified&&fresh?'passed':''}`} aria-live="polite"><div className="eval-label"><span className={`chip ${result.qualified&&fresh?'good':'neutral'}`}>{fresh?result.label:'Quote expired · recheck'}</span><span>{ageText(result.evaluated_at,now)}</span></div><div className="ev-summary"><div><span>Conservative estimated ROI</span><strong>{pct(result.net?.roi_pct,true)}</strong></div><div><span>Expected profit</span><strong>{money(result.net?.ev)}</strong></div></div>{result.net&&<><div className="metric-row"><span>ROI after probability stress</span><strong>{pct(result.net.stress_roi_pct,true)}</strong></div><div className="metric-row"><span>Maximum all-in cost at this payout</span><strong>{money(result.net.max_cost)}</strong></div>{result.net.roi_high_pct-result.net.roi_pct>.001&&<div className="metric-row"><span>Tie sensitivity ROI range</span><strong>{pct(result.net.roi_pct)} to {pct(result.net.roi_high_pct)}</strong></div>}</>}
        {!!result.reasons.length&&<div className="reasons"><h3>What prevents a screen pass</h3><ul>{result.reasons.map(r=><li key={r}>{r}</li>)}</ul></div>}
        <div className="sizing"><div className="metric-row"><span>{form.mode==='paper'?'Paper':'Actual'} entry size cap</span><strong>{result.sizing.configured?money(result.sizing.cap):'Set bankroll first'}</strong></div>{result.sizing.configured&&<p>{result.within_cap?'Entered cost is within the remaining exposure cap.':'Entered cost exceeds the current size cap.'} Recheck the slip if you change size.</p>}</div>
        <details><summary>Reference evidence ({result.probability.eligible_count} eligible / {result.probability.book_count} distinct books)</summary><div className="evidence-list">{result.probability.references.map(r=><div key={r.book}><div><strong>{r.book}</strong><span>{pct(r.probability*100)}</span></div><small>{r.eligible?'Eligible at evaluation':r.reason} · {ageText(r.observed_at,now)}{r.adjacent_lines&&` · Adjacent lines ${r.adjacent_lines.join(' / ')}`}</small></div>)}</div><p>{result.assumptions}</p></details>
        <label className="notes-label">Entry notes (optional)<textarea maxLength={1000} rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What did you observe?"/></label>
        {form.mode==='actual'&&<label className="checkbox"><input type="checkbox" checked={placed} onChange={e=>setPlaced(e.target.checked)}/><span>I already placed this manually. These are its accepted cost and payout.</span></label>}
        <button className="button secondary full" onClick={()=>void save()} disabled={busy||(form.mode==='actual'&&!placed)}><Plus size={16}/>{form.mode==='paper'?'Save paper entry':'Record accepted bet'}</button><p className="subtle small">Saving records an observation, including research-only estimates. It does not place a bet.</p>
      </section>}
      {!!row.exchange_quotes.length&&<details className="exchange-detail"><summary>Kalshi comparison · fees excluded</summary>{row.exchange_quotes.map(q=><div key={q.ticker}><strong>{(q.ask*100).toFixed(1)}¢ ask · {(q.bid*100).toFixed(1)}¢ bid</strong><p>{q.ticker}<br/>Observed {ageText(q.observed_at,now)}. This is not an Underdog execution quote.</p></div>)}</details>}
    </> }</div>
    <footer className="drawer-footer"><FlaskConical size={15}/><span>Estimated probability, not a known edge.</span></footer>
  </div></div>
}

function ReferenceForm({row,onSave}:{row:Row;onSave:()=>Promise<void>}){
  const [book,setBook]=useState('FanDuel'),[line,setLine]=useState(row.line==null?'':String(row.market==='spread'&&row.side==='away'?-row.line:row.line)),[a,setA]=useState(''),[b,setB]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('references','POST',{game_id:row.game_id,market:row.market,book,line:row.market==='moneyline'?null:Number(line),price_a:Number(a),price_b:Number(b),observed_at:new Date().toISOString(),confirmed});await onSave();setSaved(`${book} pair saved. It counts once, even if another feed carries ${book}.`);setConfirmed(false);setA('');setB('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <form onSubmit={e=>void submit(e)}><h3>Add a current sportsbook pair</h3><p className="form-intro">Enter both sides observed together, from the same full-game market. Each actual bookmaker gets one vote.</p><label>Sportsbook<select value={book} onChange={e=>setBook(e.target.value)}>{['FanDuel','BetMGM','Caesars','Pinnacle','Circa','BetRivers','BetOnline','DraftKings','Bovada'].map(b=><option key={b}>{b}</option>)}</select></label>{row.market!=='moneyline'&&<label>{row.market==='spread'?`Home-team spread (${row.game.home})`:'Point total'}<input type="number" required step="0.5" value={line} onChange={e=>setLine(e.target.value)}/><small>{row.market==='spread'?`The away side is ${line?Number(line)>0?'-'+line:'+'+Math.abs(Number(line)):'the opposite line'}.`:'Both sides must use this same total.'} For an integer quote, add each adjacent half-point pair separately.</small></label>}<div className="form-grid"><label>{row.market==='total'?'Over':row.game.home} American odds<input type="number" required step="1" placeholder="e.g. -110" value={a} onChange={e=>setA(e.target.value)}/></label><label>{row.market==='total'?'Under':row.game.away} American odds<input type="number" required step="1" placeholder="e.g. -110" value={b} onChange={e=>setB(e.target.value)}/></label></div><label className="checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I just observed both prices at this exact line. The market includes overtime, uses ordinary push/tie rules, and is open.</span></label><button className="button primary full" disabled={busy||!confirmed}><Plus size={16}/>Save observed pair</button>{error&&<div className="message error" role="alert">{error}</div>}{saved&&<div className="message success" role="status">{saved}</div>}</form>
}

function Journal({bets,onChange,onNotice}:{bets:Bet[];onChange:()=>void;onNotice:(s:string)=>void}){
  const [selected,setSelected]=useState<Bet|null>(null),[returned,setReturned]=useState(''),[outcome,setOutcome]=useState('win'),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;setBusy(true);setError('');try{await api(`bets/${selected.id}/settle`,'POST',{returned,result:outcome,notes});setSelected(null);onChange();onNotice('Settlement recorded. Entry evidence remains unchanged.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="panel"><div className="panel-heading"><h2>Entry history</h2><span className="subtle">Newest first</span></div>{!bets.length?<div className="empty"><BookOpen size={30}/><h3>Your first entry starts with a quote.</h3><p>Evaluate a selection on the odds board, then save it here.</p></div>:<div className="table-scroll"><table className="journal-table"><thead><tr><th>SELECTION</th><th>COST / RETURN</th><th>ENTRY EST. ROI</th><th>CLOSING COMPARISON</th><th>RESULT</th><th/></tr></thead><tbody>{bets.map(b=><tr key={b.id}><td><strong>{lineText(b.quote,b.game)}</strong><small>{marketName(b.quote.market)} · {b.game.away} at {b.game.home}</small><small>{shortTime(b.created_at)}</small></td><td className="number">{money(b.quote.total_cost)}<small>Win return {money(b.quote.winning_payout)}</small></td><td className="number">{pct(b.evaluation.net?.roi_pct,true)}<small>{b.evaluation.qualified?'Met screen at entry':'Research only'}</small></td><td>{b.closing?.roi_pct!=null?pct(b.closing.roi_pct,true):'—'}<small>{b.closing?.status||'Awaiting kickoff'}</small>{b.closing?.reason&&<small>{b.closing.reason}</small>}</td><td>{b.settlement?<><strong className={b.settlement.pnl>0?'positive':''}>{money(b.settlement.pnl)}</strong><small>{b.settlement.result} · returned {money(b.settlement.returned)}</small></>:<span className="chip neutral">Open</span>}</td><td><button className="button compact secondary" onClick={()=>{setSelected(b);setReturned(b.settlement?.returned||'');setOutcome(b.settlement?.result||'win');setNotes('');setError('')}}>{b.settlement?'Correct':'Settle'}</button></td></tr>)}</tbody></table></div>}{selected&&<form className="settlement-form" onSubmit={e=>void submit(e)}><div className="panel-heading"><h3>{selected.settlement?'Correct settlement':'Record actual return'} · {lineText(selected.quote,selected.game)}</h3><button className="icon-button" type="button" aria-label="Close settlement" onClick={()=>setSelected(null)}><X size={17}/></button></div><div className="form-grid three"><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}>{['win','loss','push','void','cashout','other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Total returned ($)<input type="number" step=".01" min="0" required value={returned} onChange={e=>setReturned(e.target.value)}/></label><label>Settlement notes<input maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional receipt details"/></label></div><p className="subtle">Use the total credited amount, including any refund. Corrections keep the previous settlement in the audit record.</p><button className="button primary" disabled={busy}>Save settlement</button>{error&&<div className="message error" role="alert">{error}</div>}</form>}</section>
}

function SettingsForm({settings,onSave}:{settings:Settings;onSave:(s:Settings)=>Promise<void>}){
  const [form,setForm]=useState(settings),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const fields:{key:keyof Settings;label:string;help:string;min:number;max:number;step:number}[]=[
    {key:'bankroll',label:'Configured bankroll ($)',help:'Your allocation for this activity. Update it yourself; results do not compound this value automatically.',min:0,max:10000000,step:.01},
    {key:'stake_pct',label:'Per-entry size (%)',help:'Default 0.5% of configured bankroll, subject to remaining caps.',min:.01,max:5,step:.01},
    {key:'game_cap_pct',label:'Per-game open cap (%)',help:'All open entries for a game share this cap.',min:.01,max:10,step:.01},
    {key:'open_cap_pct',label:'Total open cap (%)',help:'Paper and actual exposure are tracked separately.',min:.01,max:25,step:.01},
    {key:'min_roi_pct',label:'Minimum estimated ROI (%)',help:'Applied to the least favorable tie scenario after fees.',min:0,max:50,step:.1},
    {key:'stress_pp',label:'Probability stress (percentage points)',help:'Move this much probability from win to loss.',min:.5,max:10,step:.1},
    {key:'min_books',label:'Minimum eligible sportsbooks',help:'Distinct books with complete, fresh pairs. Kalshi does not count.',min:3,max:9,step:1},
    {key:'max_age_seconds',label:'Maximum quote age (seconds)',help:'Applies to direct/manual references and entered Underdog quotes.',min:30,max:300,step:1},
    {key:'max_disagreement_pp',label:'Maximum book disagreement (points)',help:'Difference between highest and lowest estimated win probability.',min:1,max:10,step:.1},
    {key:'tie_max_pct',label:'Regular-season tie sensitivity (%)',help:'Upper end of an assumed sensitivity range, not a measured tie probability.',min:0,max:10,step:.1},
  ]
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await onSave(form)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <form className="panel settings-form" onSubmit={e=>void submit(e)}><div className="panel-heading"><div><h2>Bankroll & screening</h2><span className="subtle">Changes apply to new evaluations. Saved entry evidence stays fixed.</span></div><Settings2 size={20}/></div><div className="settings-fields">{fields.map(f=><label key={f.key}>{f.label}<input type="number" required min={f.min} max={f.max} step={f.step} value={form[f.key]} onChange={e=>setForm(s=>({...s,[f.key]:f.key==='bankroll'?e.target.value:Number(e.target.value)}))}/><small>{f.help}</small></label>)}</div><div className="settings-actions"><button className="button primary" disabled={busy}><Check size={16}/>Save settings</button><span className="subtle">Saved to your local SQLite database.</span></div>{error&&<div className="message error" role="alert">{error}</div>}</form>
}

createRoot(document.getElementById('root')!).render(<App/> )
